# This workflow checks out the code, builds the .NET project,
# and implicitly runs the security analyzers. It uses Security Code Scan
# and .NET Security Guard

name: .NET CI Build and Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions: 
  contents: read
  security-events: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore
      # Builds the project, which automatically runs the installed
      # analyzers, Security Code Scan and SecurityGuard.
    - name: Build and Scan for Security Issues
      run: dotnet build --configuration Release --no-restore
