name: Semgrep + DevSkim

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write          

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ---------- Semgrep ----------
      - uses: returntocorp/semgrep-action@v1
        with:
          config: p/security-audit
          generateSarif: true
          sarifOutput: semgrep.sarif

      - uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep.sarif
          category: semgrep

      # ---------- DevSkim ----------
      - uses: microsoft/DevSkim-Action@v1
        with:
          directory-to-scan: ./
          should-scan-archives: false

      - uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: ${{ github.workspace }}/devskim-results.sarif
          category: devskim
