# This workflow uses actions that are not certified by GitHub.

name: Semgrep

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  schedule:
    - cron: '28 5 * * 0'

permissions:
  contents: read

jobs:
  semgrep:
    permissions:
      contents: read 
      security-events: write 
      actions: read 
    name: Scan
    runs-on: ubuntu-latest
    steps:
      # Checkout project source
      - uses: actions/checkout@v4

      - name: Install Semgrep CLI
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run Semgrep and generate SARIF
        run: |
          semgrep --config auto --sarif --output semgrep.sarif .

      # Upload SARIF file generated in previous step
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always()
